### ISSUE TITLE
undo doesn't restore grass

### ISSUE THREAD

**Issue by gnembon** [Ghoulboy78/World-edit-scarpet#14]
select an area  of natural terrain and fill it with stone, then undo. Grass doesn't show up

Reason - we place blocks from the bottom up and with updates which causes grass to pop off and then when that block is taken care of its air.

Blocks could also break other blocks from sides (beds) or all directions (extended pistons). Suggest doing all ops without updates, and then call updates extra if they are not supressed.

**Comment by replaceitem** [comment]
for fill/stack/... there is the -u flag to prevent updates, should also be added to undo (or maybe even by default?)
see #16

**Comment by Ghoulboy78** [comment]
hmm, interesting

**Comment by Ghoulboy78** [comment]
ye, replaceitem beat me to it

**Comment by Ghoulboy78** [comment]
Fixed with the addition of no update flags
