### ISSUE TITLE
-a and -w flags should work differently

### ISSUE THREAD

**Issue by Firigion** [Ghoulboy78/World-edit-scarpet#21]
If I'm not mistaken, `-a` flag in world edit means that, when pasting from clipboard or doing other copy-like operations, air should be skipped. Right now scarpet WE uses `-a` to signify "paste or set only replacing air" and added the new flag `-p` to reproduce the original WE's functionality. I propose swaping those two to maintain parity.

The other flag that needs being discussed about is `-w`: when it was original proposed the idea was that if set to `true`, blocks that can be waterlogged should be waterlogged when being set in a position that was previously water. That goes both for filling an area or shape and for copy-like operations. Right now, `-w` is used as a "don't  keep waterlogable blocks waterlogged". I porpose adding a new `-d` flag for "dry" that will remove waterlog status from waterlogged blocks in copy-like operations and `-w` be moved to mean the originally intended thing: waterlog if target air is water.

**Comment by Ghoulboy78** [comment]
umm, actually in the code for `set_block` function currently the `-w` flag does exactly what you describe. But i do agree that `-d` flag would be useful. Also line 624 would need to be changed to `if(flags~'w' && (existing == 'water' && block_state(existing,'level')) || block_state(_,'waterlogged')=='true' == '0',put(state,'waterlogged','true'));`

**Comment by Ghoulboy78** [comment]
And there also would need to be the case that if you're setting to air, and the flag is true, and the `-w` flag is true, then set to watr, not air.

**Comment by Firigion** [comment]
I didn't read the code, I read the docu, my bad. Didn't understand the second comment.
