### ISSUE TITLE
Suggestion: -g and -s flags

### ISSUE THREAD

**Issue by Firigion** [Ghoulboy78/World-edit-scarpet#23]
`-g` should make it so greenery (or vegetation, and make the flag `-v`) like tall grass, flowers, sea grass and kelp is replaced along air/water. So making a fill command replace water will also replace seagrass and kelp, for example. Coral fans, sea pickles and dead bushes could be added too, up for debate.

-s flag is for "soft replace": when reaplcing a block by another similar block that shares the properties of the first (replacing stair with stair of different material, logs of different kinds, logs with wood and so on), the properties should remain untouched. For example, if in the affected area theres a few top side acacia staris and a few bottom side acacia staris, replacing acacia staris with cobble ones will make the top acacia into top cobble an the bottom acacia into bottom cobble.

**Comment by Ghoulboy78** [comment]
wait, do u mean replacing like grass with seagrass?

**Comment by Firigion** [comment]
no, I meant that when replacing water (and flowing water) if -g is true, seagrass and kelp should be replaced too. Same goes for ehwn replacing air -g: should replace air, tall grass, ferns and maybe flowers and/or dead bushes.
