### ISSUE TITLE
Selecting using __on_player_swings_hand does not work on my system

### ISSUE THREAD

**Issue by random-j-farmer** [Ghoulboy78/World-edit-scarpet#37]
Playing on 1.16.4 / Java 14 / MacOS 10.13.6

Selecting the first block works, but the second does not, so I can not get a selection to use with the commands which confused me at first.

If I comment out `__on_player_swings_hand` and use `__on_player_clicks_block`, it works.

Love the app, it lives in my global script directory now :)

Don't know if other people have this issue, it might be MacOS related
because of the One-Mousebutton thing (my mouse has more buttons,
but I suspect mouse events are a little different on MacOS).  Also note that my version of MacOS is not current - I don't want the Catalina "Notarize your Software" hassle.  So maybe it is just because my system is a very special snowflake.

**Comment by Ghoulboy78** [comment]
No, it's jsu that were dumb and are using unreleased veriosn of fabric-carpet. Use that or wait for next 1.17 release for the app to work properly.
