### ISSUE TITLE
Add other shapes and non-WE stuff

### ISSUE THREAD

**Issue by Ghoulboy78** [Ghoulboy78/World-edit-scarpet#4]
Extra stuff thats not strictly WE, but useful anyways

- [x] Spheres/balls
- [x] Pyramids/prisms (basically /draw command shapes)
- [x] In-game help menu

**Comment by Ghoulboy78** [comment]
im thinking that this should be in the brush tool functionality

**Comment by gnembon** [comment]
man, you need to have a spray-paint for sure

**Comment by Ghoulboy78** [comment]
maybe even with cool visual effect!
