### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by Firigion** [Ghoulboy78/World-edit-scarpet#44]
Let's make a thread here with options for new names that we can vote on. 

My proposal is have a separate comment for each proposed name and anyone can vote on as many names as they want by reacting to the comments. We can have both a "full" official name and a a shorthand used as the base command. The comment proposing a name can also have a few short sentences stating why they think it's good. 

To quote gnembon: "[...] the name of the app should be simple enough it rolls from command prompt. /we is good, cause on qwerty its just next to each other."

For example, for the current name:
**Full:** world-edit (or world-edit-scarpet?)
**Command:** `/world_edit`
**Features:** Clashes and creates confusion with the actual world-edit mod/plugin. It's also long to write when using commands.

Upvote this comment if you'd like to keep the current name.

**Comment by Firigion** [comment]
**Full:** world-edit
**Command:** `/we`
**Features:** Easier to type; we don't need to change a bunch of thext in the app to accomodate for the new name, just suggested commands.

**Comment by Firigion** [comment]
**Full:** scarpet-edit
**Command:** `/se`
**Features:** Really easy to type too; play on the name of other world-edit type stuff (world edit, bling edit, prolly some others)

**Comment by Firigion** [comment]
**Full:** paint-app
**Command:** `/pa`
**Features:** Some may argue it's harder to type, because it's two hands, some may argue its easier, for the same reason. Name is a bit lame, tho.

**Comment by Firigion** [comment]
**Full:** worldoshop
**Command:** `/ws`
**Features:** idk, gnembon proposed it a while back. Command is still good in qwerty keyboards.

**Comment by altrisi** [comment]
I think Github Discussions (if available for this repo, not sure if there are requirements) would be better suited for this issue, since it basically makes a "thread" for each base reply, so each of the options could be discussed on its own.

**Comment by Firigion** [comment]
Yes, that's a good idea; I wasn't aware of that feature.

I don't think the hyphen is necessary, no, in particular since that name will only appear in some text in chat like help menu, and in the documentation. We can choose if we want a hyphen, two words or PascalCase it.

**Comment by Ghoulboy78** [comment]
yo @Firigion you can move the suggestions to #47 (a discussion) and close this.
