### ISSUE TITLE
Undo is not dimension specific

### ISSUE THREAD

**Issue by Firigion** [Ghoulboy78/World-edit-scarpet#48]
When executing an operation in a dimension, and then moving to another dimension, `undo` will try to well, _undo_ what had been done, without taking into consideration the dimension it was done in, meaning you end up with the app pasting in a bunch of blocks in the wrong dimension

This is the result after filling in a cube with air in the nether, going to the same coordiantes in the ow and running `/world-edit undo`:
![image](https://user-images.githubusercontent.com/64820010/106412940-9b7b8e00-6427-11eb-858f-4d0b443dec69.png)

To avoid this, I suggest using dimension specific undo histories, saved in a map with the dimension name as key. That can potentially also support custom dimensions, if done right.

**Comment by Ghoulboy78** [comment]
ah oops
